id: P003156
initial_creation_type: ocr
source_metadata:
  id: bdr:W30410
  title: ངེས་དོན་དགའ་ཚལ།
  author: ''
  volumes:
    85e6f5e5b1674bceb723b1de2225773d:
      image_group_id: I1KG26253
      title: ''
      volume_number: 1
      total_pages: 0
    17bb9c5add0043cd94261a114436a128:
      image_group_id: I1KG26254
      title: ''
      volume_number: 2
      total_pages: 133
    c7cce4a53b744bb0bcb088df2004fe5c:
      image_group_id: I1KG26255
      title: ''
      volume_number: 3
      total_pages: 0
    4b11cddf01854820a7886b17828fab1b:
      image_group_id: I1KG26256
      title: ''
      volume_number: 4
      total_pages: 0
    7dd31f8a554f4050a820ebf1c1917a5a:
      image_group_id: I1KG26257
      title: ''
      volume_number: 5
      total_pages: 152
    ca6f4647785e477b8861e233ef10c270:
      image_group_id: I1KG26258
      title: ''
      volume_number: 6
      total_pages: 128
    af58cf37d0414258a74a12fd58736d3d:
      image_group_id: I1KG26259
      title: ''
      volume_number: 7
      total_pages: 0
    0126ce45d6a642e4b56799f529b95c77:
      image_group_id: I1KG26260
      title: ''
      volume_number: 8
      total_pages: 0
    50e7148e07e3431e9eb9aa42d7738f9a:
      image_group_id: I1KG26261
      title: ''
      volume_number: 9
      total_pages: 0
    c1262f046a54409c8700502563a7b7a0:
      image_group_id: I1KG26262
      title: ''
      volume_number: 10
      total_pages: 0
    f93ff48a5e7e403ea1dcc1d43e0e4972:
      image_group_id: I1KG26263
      title: ''
      volume_number: 11
      total_pages: 0
    b92b9b0b77b34869bc4633bbbec47fc5:
      image_group_id: I1KG26264
      title: ''
      volume_number: 12
      total_pages: 0
    075e873eb8bb492abdcf513f77d1ba5e:
      image_group_id: I1KG26265
      title: ''
      volume_number: 13
      total_pages: 0
    72f46bd87f9a4aedb13f5ddf80a01ebf:
      image_group_id: I1KG26266
      title: ''
      volume_number: 14
      total_pages: 0
    319972170e374b84924fd56c0c0baab3:
      image_group_id: I1KG26267
      title: ''
      volume_number: 15
      total_pages: 0
    ef9b2a40636b4f9bb743036d3f7d9018:
      image_group_id: I1KG26268
      title: ''
      volume_number: 16
      total_pages: 0
    150e745731a949509a65e88909523bbd:
      image_group_id: I1KG26269
      title: ''
      volume_number: 17
      total_pages: 0
    19f1cfb03ca44c64b92fba2d15b2bbd0:
      image_group_id: I1KG26270
      title: ''
      volume_number: 18
      total_pages: 0
    b0b333a48f5a497f9ef996539224f429:
      image_group_id: I1KG26271
      title: ''
      volume_number: 19
      total_pages: 0
    2aa1a162dbc44f9db7e2615ea86b3c88:
      image_group_id: I1KG26272
      title: ''
      volume_number: 20
      total_pages: 0
